// Code generated by protoc-gen-go. DO NOT EDIT.
// source: basecall.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
type ProcessSubmission2 struct {
	Val1                 string   `protobuf:"bytes,1,opt,name=val1,proto3" json:"val1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessSubmission2) Reset()         { *m = ProcessSubmission2{} }
func (m *ProcessSubmission2) String() string { return proto.CompactTextString(m) }
func (*ProcessSubmission2) ProtoMessage()    {}
func (*ProcessSubmission2) Descriptor() ([]byte, []int) {
	return fileDescriptor_fac72c8d4e7e2e2a, []int{0}
}

func (m *ProcessSubmission2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessSubmission2.Unmarshal(m, b)
}
func (m *ProcessSubmission2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessSubmission2.Marshal(b, m, deterministic)
}
func (m *ProcessSubmission2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessSubmission2.Merge(m, src)
}
func (m *ProcessSubmission2) XXX_Size() int {
	return xxx_messageInfo_ProcessSubmission2.Size(m)
}
func (m *ProcessSubmission2) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessSubmission2.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessSubmission2 proto.InternalMessageInfo

func (m *ProcessSubmission2) GetVal1() string {
	if m != nil {
		return m.Val1
	}
	return ""
}

//
type ProcessSummary2 struct {
	Val2                 string   `protobuf:"bytes,1,opt,name=val2,proto3" json:"val2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessSummary2) Reset()         { *m = ProcessSummary2{} }
func (m *ProcessSummary2) String() string { return proto.CompactTextString(m) }
func (*ProcessSummary2) ProtoMessage()    {}
func (*ProcessSummary2) Descriptor() ([]byte, []int) {
	return fileDescriptor_fac72c8d4e7e2e2a, []int{1}
}

func (m *ProcessSummary2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessSummary2.Unmarshal(m, b)
}
func (m *ProcessSummary2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessSummary2.Marshal(b, m, deterministic)
}
func (m *ProcessSummary2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessSummary2.Merge(m, src)
}
func (m *ProcessSummary2) XXX_Size() int {
	return xxx_messageInfo_ProcessSummary2.Size(m)
}
func (m *ProcessSummary2) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessSummary2.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessSummary2 proto.InternalMessageInfo

func (m *ProcessSummary2) GetVal2() string {
	if m != nil {
		return m.Val2
	}
	return ""
}

func init() {
	proto.RegisterType((*ProcessSubmission2)(nil), "services.ProcessSubmission2")
	proto.RegisterType((*ProcessSummary2)(nil), "services.ProcessSummary2")
}

func init() { proto.RegisterFile("basecall.proto", fileDescriptor_fac72c8d4e7e2e2a) }

var fileDescriptor_fac72c8d4e7e2e2a = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x4a, 0x2c, 0x4e,
	0x4d, 0x4e, 0xcc, 0xc9, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x28, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x2d, 0x56, 0xd2, 0xe0, 0x12, 0x0a, 0x28, 0xca, 0x4f, 0x4e, 0x2d, 0x2e, 0x0e,
	0x2e, 0x4d, 0xca, 0xcd, 0x2c, 0x2e, 0xce, 0xcc, 0xcf, 0x33, 0x12, 0x12, 0xe2, 0x62, 0x29, 0x4b,
	0xcc, 0x31, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x54, 0xb9, 0xf8, 0xe1,
	0x2a, 0x73, 0x73, 0x13, 0x8b, 0x2a, 0x61, 0xca, 0x8c, 0x90, 0x94, 0x19, 0x19, 0x85, 0x73, 0x71,
	0x38, 0x41, 0x2d, 0x13, 0xf2, 0xe6, 0xe2, 0x0b, 0x2a, 0xcd, 0x83, 0x71, 0x33, 0xf3, 0xd2, 0x85,
	0x64, 0xf4, 0x60, 0x36, 0xeb, 0x61, 0x5a, 0x2b, 0x25, 0x89, 0x45, 0x16, 0x62, 0x95, 0x12, 0x43,
	0x12, 0x1b, 0xd8, 0xe9, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9e, 0xfe, 0xe8, 0xf3, 0xcc,
	0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BasecallClient is the client API for Basecall service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BasecallClient interface {
	// Run is an exposed function for the Basecall service
	RunBasecalling(ctx context.Context, in *ProcessSubmission2, opts ...grpc.CallOption) (*ProcessSummary2, error)
}

type basecallClient struct {
	cc *grpc.ClientConn
}

func NewBasecallClient(cc *grpc.ClientConn) BasecallClient {
	return &basecallClient{cc}
}

func (c *basecallClient) RunBasecalling(ctx context.Context, in *ProcessSubmission2, opts ...grpc.CallOption) (*ProcessSummary2, error) {
	out := new(ProcessSummary2)
	err := c.cc.Invoke(ctx, "/services.Basecall/RunBasecalling", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BasecallServer is the server API for Basecall service.
type BasecallServer interface {
	// Run is an exposed function for the Basecall service
	RunBasecalling(context.Context, *ProcessSubmission2) (*ProcessSummary2, error)
}

// UnimplementedBasecallServer can be embedded to have forward compatible implementations.
type UnimplementedBasecallServer struct {
}

func (*UnimplementedBasecallServer) RunBasecalling(ctx context.Context, req *ProcessSubmission2) (*ProcessSummary2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunBasecalling not implemented")
}

func RegisterBasecallServer(s *grpc.Server, srv BasecallServer) {
	s.RegisterService(&_Basecall_serviceDesc, srv)
}

func _Basecall_RunBasecalling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessSubmission2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasecallServer).RunBasecalling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.Basecall/RunBasecalling",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasecallServer).RunBasecalling(ctx, req.(*ProcessSubmission2))
	}
	return interceptor(ctx, in, info, handler)
}

var _Basecall_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.Basecall",
	HandlerType: (*BasecallServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunBasecalling",
			Handler:    _Basecall_RunBasecalling_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "basecall.proto",
}
