// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.3
// source: service_sequence.proto

package services

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//
type ProcessSubmission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val1 string `protobuf:"bytes,1,opt,name=val1,proto3" json:"val1,omitempty"`
}

func (x *ProcessSubmission) Reset() {
	*x = ProcessSubmission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_sequence_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessSubmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessSubmission) ProtoMessage() {}

func (x *ProcessSubmission) ProtoReflect() protoreflect.Message {
	mi := &file_service_sequence_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessSubmission.ProtoReflect.Descriptor instead.
func (*ProcessSubmission) Descriptor() ([]byte, []int) {
	return file_service_sequence_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessSubmission) GetVal1() string {
	if x != nil {
		return x.Val1
	}
	return ""
}

//
type ProcessSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val2 string `protobuf:"bytes,1,opt,name=val2,proto3" json:"val2,omitempty"`
}

func (x *ProcessSummary) Reset() {
	*x = ProcessSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_sequence_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessSummary) ProtoMessage() {}

func (x *ProcessSummary) ProtoReflect() protoreflect.Message {
	mi := &file_service_sequence_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessSummary.ProtoReflect.Descriptor instead.
func (*ProcessSummary) Descriptor() ([]byte, []int) {
	return file_service_sequence_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessSummary) GetVal2() string {
	if x != nil {
		return x.Val2
	}
	return ""
}

var File_service_sequence_proto protoreflect.FileDescriptor

var file_service_sequence_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x22, 0x27, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x6c, 0x31, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x61, 0x6c, 0x31, 0x22, 0x24, 0x0a, 0x0e, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x76, 0x61, 0x6c, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x61, 0x6c,
	0x32, 0x32, 0x54, 0x0a, 0x08, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x48, 0x0a,
	0x0d, 0x52, 0x75, 0x6e, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x69, 0x6e, 0x67, 0x12, 0x1b,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x18, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_sequence_proto_rawDescOnce sync.Once
	file_service_sequence_proto_rawDescData = file_service_sequence_proto_rawDesc
)

func file_service_sequence_proto_rawDescGZIP() []byte {
	file_service_sequence_proto_rawDescOnce.Do(func() {
		file_service_sequence_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_sequence_proto_rawDescData)
	})
	return file_service_sequence_proto_rawDescData
}

var file_service_sequence_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_sequence_proto_goTypes = []interface{}{
	(*ProcessSubmission)(nil), // 0: services.ProcessSubmission
	(*ProcessSummary)(nil),    // 1: services.ProcessSummary
}
var file_service_sequence_proto_depIdxs = []int32{
	0, // 0: services.Sequence.RunSequencing:input_type -> services.ProcessSubmission
	1, // 1: services.Sequence.RunSequencing:output_type -> services.ProcessSummary
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_sequence_proto_init() }
func file_service_sequence_proto_init() {
	if File_service_sequence_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_sequence_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessSubmission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_sequence_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_sequence_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_sequence_proto_goTypes,
		DependencyIndexes: file_service_sequence_proto_depIdxs,
		MessageInfos:      file_service_sequence_proto_msgTypes,
	}.Build()
	File_service_sequence_proto = out.File
	file_service_sequence_proto_rawDesc = nil
	file_service_sequence_proto_goTypes = nil
	file_service_sequence_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SequenceClient is the client API for Sequence service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SequenceClient interface {
	// Run is an exposed function for the Sequence service
	RunSequencing(ctx context.Context, in *ProcessSubmission, opts ...grpc.CallOption) (*ProcessSummary, error)
}

type sequenceClient struct {
	cc grpc.ClientConnInterface
}

func NewSequenceClient(cc grpc.ClientConnInterface) SequenceClient {
	return &sequenceClient{cc}
}

func (c *sequenceClient) RunSequencing(ctx context.Context, in *ProcessSubmission, opts ...grpc.CallOption) (*ProcessSummary, error) {
	out := new(ProcessSummary)
	err := c.cc.Invoke(ctx, "/services.Sequence/RunSequencing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SequenceServer is the server API for Sequence service.
type SequenceServer interface {
	// Run is an exposed function for the Sequence service
	RunSequencing(context.Context, *ProcessSubmission) (*ProcessSummary, error)
}

// UnimplementedSequenceServer can be embedded to have forward compatible implementations.
type UnimplementedSequenceServer struct {
}

func (*UnimplementedSequenceServer) RunSequencing(context.Context, *ProcessSubmission) (*ProcessSummary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunSequencing not implemented")
}

func RegisterSequenceServer(s *grpc.Server, srv SequenceServer) {
	s.RegisterService(&_Sequence_serviceDesc, srv)
}

func _Sequence_RunSequencing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessSubmission)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SequenceServer).RunSequencing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.Sequence/RunSequencing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SequenceServer).RunSequencing(ctx, req.(*ProcessSubmission))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sequence_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.Sequence",
	HandlerType: (*SequenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunSequencing",
			Handler:    _Sequence_RunSequencing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_sequence.proto",
}
