// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.3
// source: service_basecall.proto

package services

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//
type ProcessSubmission2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val1 string `protobuf:"bytes,1,opt,name=val1,proto3" json:"val1,omitempty"`
}

func (x *ProcessSubmission2) Reset() {
	*x = ProcessSubmission2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_basecall_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessSubmission2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessSubmission2) ProtoMessage() {}

func (x *ProcessSubmission2) ProtoReflect() protoreflect.Message {
	mi := &file_service_basecall_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessSubmission2.ProtoReflect.Descriptor instead.
func (*ProcessSubmission2) Descriptor() ([]byte, []int) {
	return file_service_basecall_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessSubmission2) GetVal1() string {
	if x != nil {
		return x.Val1
	}
	return ""
}

//
type ProcessSummary2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val2 string `protobuf:"bytes,1,opt,name=val2,proto3" json:"val2,omitempty"`
}

func (x *ProcessSummary2) Reset() {
	*x = ProcessSummary2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_basecall_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessSummary2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessSummary2) ProtoMessage() {}

func (x *ProcessSummary2) ProtoReflect() protoreflect.Message {
	mi := &file_service_basecall_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessSummary2.ProtoReflect.Descriptor instead.
func (*ProcessSummary2) Descriptor() ([]byte, []int) {
	return file_service_basecall_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessSummary2) GetVal2() string {
	if x != nil {
		return x.Val2
	}
	return ""
}

var File_service_basecall_proto protoreflect.FileDescriptor

var file_service_basecall_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x63, 0x61,
	0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x22, 0x28, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x6c, 0x31,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x61, 0x6c, 0x31, 0x22, 0x25, 0x0a, 0x0f,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x32, 0x12,
	0x12, 0x0a, 0x04, 0x76, 0x61, 0x6c, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76,
	0x61, 0x6c, 0x32, 0x32, 0x57, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x12,
	0x4b, 0x0a, 0x0e, 0x52, 0x75, 0x6e, 0x42, 0x61, 0x73, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e,
	0x67, 0x12, 0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x32, 0x1a,
	0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x32, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_basecall_proto_rawDescOnce sync.Once
	file_service_basecall_proto_rawDescData = file_service_basecall_proto_rawDesc
)

func file_service_basecall_proto_rawDescGZIP() []byte {
	file_service_basecall_proto_rawDescOnce.Do(func() {
		file_service_basecall_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_basecall_proto_rawDescData)
	})
	return file_service_basecall_proto_rawDescData
}

var file_service_basecall_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_basecall_proto_goTypes = []interface{}{
	(*ProcessSubmission2)(nil), // 0: services.ProcessSubmission2
	(*ProcessSummary2)(nil),    // 1: services.ProcessSummary2
}
var file_service_basecall_proto_depIdxs = []int32{
	0, // 0: services.Basecall.RunBasecalling:input_type -> services.ProcessSubmission2
	1, // 1: services.Basecall.RunBasecalling:output_type -> services.ProcessSummary2
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_basecall_proto_init() }
func file_service_basecall_proto_init() {
	if File_service_basecall_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_basecall_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessSubmission2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_basecall_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessSummary2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_basecall_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_basecall_proto_goTypes,
		DependencyIndexes: file_service_basecall_proto_depIdxs,
		MessageInfos:      file_service_basecall_proto_msgTypes,
	}.Build()
	File_service_basecall_proto = out.File
	file_service_basecall_proto_rawDesc = nil
	file_service_basecall_proto_goTypes = nil
	file_service_basecall_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BasecallClient is the client API for Basecall service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BasecallClient interface {
	// Run is an exposed function for the Basecall service
	RunBasecalling(ctx context.Context, in *ProcessSubmission2, opts ...grpc.CallOption) (*ProcessSummary2, error)
}

type basecallClient struct {
	cc grpc.ClientConnInterface
}

func NewBasecallClient(cc grpc.ClientConnInterface) BasecallClient {
	return &basecallClient{cc}
}

func (c *basecallClient) RunBasecalling(ctx context.Context, in *ProcessSubmission2, opts ...grpc.CallOption) (*ProcessSummary2, error) {
	out := new(ProcessSummary2)
	err := c.cc.Invoke(ctx, "/services.Basecall/RunBasecalling", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BasecallServer is the server API for Basecall service.
type BasecallServer interface {
	// Run is an exposed function for the Basecall service
	RunBasecalling(context.Context, *ProcessSubmission2) (*ProcessSummary2, error)
}

// UnimplementedBasecallServer can be embedded to have forward compatible implementations.
type UnimplementedBasecallServer struct {
}

func (*UnimplementedBasecallServer) RunBasecalling(context.Context, *ProcessSubmission2) (*ProcessSummary2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunBasecalling not implemented")
}

func RegisterBasecallServer(s *grpc.Server, srv BasecallServer) {
	s.RegisterService(&_Basecall_serviceDesc, srv)
}

func _Basecall_RunBasecalling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessSubmission2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasecallServer).RunBasecalling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.Basecall/RunBasecalling",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasecallServer).RunBasecalling(ctx, req.(*ProcessSubmission2))
	}
	return interceptor(ctx, in, info, handler)
}

var _Basecall_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.Basecall",
	HandlerType: (*BasecallServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunBasecalling",
			Handler:    _Basecall_RunBasecalling_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_basecall.proto",
}
