// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sample.proto

package sample

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
//Status is used to determine if the sample is untagged, tagged or in the announcment queue
type Status int32

const (
	Status_UN_INITIALIZED Status = 0
	Status_untagged       Status = 1
	Status_tagged         Status = 2
	Status_announced      Status = 3
)

var Status_name = map[int32]string{
	0: "UN_INITIALIZED",
	1: "untagged",
	2: "tagged",
	3: "announced",
}

var Status_value = map[string]int32{
	"UN_INITIALIZED": 0,
	"untagged":       1,
	"tagged":         2,
	"announced":      3,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2141552de9bf11d0, []int{0}
}

//
//Sample is used describe the start point of a sequencing experiment
type Sample struct {
	Created              *timestamp.Timestamp `protobuf:"bytes,1,opt,name=created,proto3" json:"created,omitempty"`
	Label                string               `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Status               Status               `protobuf:"varint,3,opt,name=status,proto3,enum=sample.Status" json:"status,omitempty"`
	Barcode              int32                `protobuf:"varint,4,opt,name=barcode,proto3" json:"barcode,omitempty"`
	History              []*Sample_Comment    `protobuf:"bytes,5,rep,name=history,proto3" json:"history,omitempty"`
	Tags                 *Sample_Tags         `protobuf:"bytes,6,opt,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Sample) Reset()         { *m = Sample{} }
func (m *Sample) String() string { return proto.CompactTextString(m) }
func (*Sample) ProtoMessage()    {}
func (*Sample) Descriptor() ([]byte, []int) {
	return fileDescriptor_2141552de9bf11d0, []int{0}
}

func (m *Sample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sample.Unmarshal(m, b)
}
func (m *Sample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sample.Marshal(b, m, deterministic)
}
func (m *Sample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sample.Merge(m, src)
}
func (m *Sample) XXX_Size() int {
	return xxx_messageInfo_Sample.Size(m)
}
func (m *Sample) XXX_DiscardUnknown() {
	xxx_messageInfo_Sample.DiscardUnknown(m)
}

var xxx_messageInfo_Sample proto.InternalMessageInfo

func (m *Sample) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Sample) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Sample) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_UN_INITIALIZED
}

func (m *Sample) GetBarcode() int32 {
	if m != nil {
		return m.Barcode
	}
	return 0
}

func (m *Sample) GetHistory() []*Sample_Comment {
	if m != nil {
		return m.History
	}
	return nil
}

func (m *Sample) GetTags() *Sample_Tags {
	if m != nil {
		return m.Tags
	}
	return nil
}

//
//Comments are used by Herald to record a samples history
type Sample_Comment struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Text                 string               `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Sample_Comment) Reset()         { *m = Sample_Comment{} }
func (m *Sample_Comment) String() string { return proto.CompactTextString(m) }
func (*Sample_Comment) ProtoMessage()    {}
func (*Sample_Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_2141552de9bf11d0, []int{0, 0}
}

func (m *Sample_Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sample_Comment.Unmarshal(m, b)
}
func (m *Sample_Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sample_Comment.Marshal(b, m, deterministic)
}
func (m *Sample_Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sample_Comment.Merge(m, src)
}
func (m *Sample_Comment) XXX_Size() int {
	return xxx_messageInfo_Sample_Comment.Size(m)
}
func (m *Sample_Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Sample_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Sample_Comment proto.InternalMessageInfo

func (m *Sample_Comment) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Sample_Comment) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

//
//Tags are used to indicate what processes to run on a sample
type Sample_Tags struct {
	Sequence             bool     `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sample_Tags) Reset()         { *m = Sample_Tags{} }
func (m *Sample_Tags) String() string { return proto.CompactTextString(m) }
func (*Sample_Tags) ProtoMessage()    {}
func (*Sample_Tags) Descriptor() ([]byte, []int) {
	return fileDescriptor_2141552de9bf11d0, []int{0, 1}
}

func (m *Sample_Tags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sample_Tags.Unmarshal(m, b)
}
func (m *Sample_Tags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sample_Tags.Marshal(b, m, deterministic)
}
func (m *Sample_Tags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sample_Tags.Merge(m, src)
}
func (m *Sample_Tags) XXX_Size() int {
	return xxx_messageInfo_Sample_Tags.Size(m)
}
func (m *Sample_Tags) XXX_DiscardUnknown() {
	xxx_messageInfo_Sample_Tags.DiscardUnknown(m)
}

var xxx_messageInfo_Sample_Tags proto.InternalMessageInfo

func (m *Sample_Tags) GetSequence() bool {
	if m != nil {
		return m.Sequence
	}
	return false
}

func init() {
	proto.RegisterEnum("sample.Status", Status_name, Status_value)
	proto.RegisterType((*Sample)(nil), "sample.Sample")
	proto.RegisterType((*Sample_Comment)(nil), "sample.Sample.Comment")
	proto.RegisterType((*Sample_Tags)(nil), "sample.Sample.Tags")
}

func init() { proto.RegisterFile("sample.proto", fileDescriptor_2141552de9bf11d0) }

var fileDescriptor_2141552de9bf11d0 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xc1, 0x4f, 0xab, 0x40,
	0x10, 0xc6, 0x1f, 0x2d, 0x85, 0x76, 0xda, 0xd7, 0x34, 0xf3, 0x5e, 0xcc, 0x86, 0x8b, 0xa4, 0x07,
	0x25, 0x1e, 0xa8, 0xa9, 0x1e, 0xbc, 0x1a, 0xed, 0x81, 0xc4, 0xf4, 0xb0, 0xad, 0x31, 0xf1, 0x62,
	0x16, 0x18, 0xb1, 0x09, 0xb0, 0x95, 0x5d, 0x12, 0xfd, 0xa7, 0xfd, 0x1b, 0x8c, 0x0b, 0xd4, 0xc4,
	0x93, 0x27, 0xe6, 0x1b, 0x7e, 0xdf, 0xec, 0x37, 0x03, 0x13, 0x25, 0x8a, 0x7d, 0x4e, 0xe1, 0xbe,
	0x92, 0x5a, 0xa2, 0xd3, 0x28, 0xef, 0x38, 0x93, 0x32, 0xcb, 0x69, 0x61, 0xba, 0x71, 0xfd, 0xbc,
	0xd0, 0xbb, 0x82, 0x94, 0x16, 0xc5, 0xbe, 0x01, 0xe7, 0x1f, 0x3d, 0x70, 0x36, 0x86, 0xc5, 0x4b,
	0x70, 0x93, 0x8a, 0x84, 0xa6, 0x94, 0x59, 0xbe, 0x15, 0x8c, 0x97, 0x5e, 0xd8, 0xb8, 0xc3, 0xce,
	0x1d, 0x6e, 0x3b, 0x37, 0xef, 0x50, 0xfc, 0x0f, 0x83, 0x5c, 0xc4, 0x94, 0xb3, 0x9e, 0x6f, 0x05,
	0x23, 0xde, 0x08, 0x3c, 0x01, 0x47, 0x69, 0xa1, 0x6b, 0xc5, 0xfa, 0xbe, 0x15, 0x4c, 0x97, 0xd3,
	0xb0, 0x8d, 0xb7, 0x31, 0x5d, 0xde, 0xfe, 0x45, 0x06, 0x6e, 0x2c, 0xaa, 0x44, 0xa6, 0xc4, 0x6c,
	0xdf, 0x0a, 0x06, 0xbc, 0x93, 0x78, 0x0e, 0xee, 0xcb, 0x4e, 0x69, 0x59, 0xbd, 0xb3, 0x81, 0xdf,
	0x0f, 0xc6, 0xcb, 0xa3, 0xc3, 0x88, 0xe6, 0x73, 0x23, 0x8b, 0x82, 0x4a, 0xcd, 0x3b, 0x0c, 0x4f,
	0xc1, 0xd6, 0x22, 0x53, 0xcc, 0x31, 0xe1, 0xff, 0xfd, 0xc0, 0xb7, 0x22, 0x53, 0xdc, 0x00, 0xde,
	0x03, 0xb8, 0xad, 0x19, 0xaf, 0x60, 0x74, 0xb8, 0xc8, 0x2f, 0xb6, 0xfe, 0x86, 0x11, 0xc1, 0xd6,
	0xf4, 0xa6, 0xdb, 0xb5, 0x4d, 0xed, 0xcd, 0xc1, 0xfe, 0x7a, 0x06, 0x3d, 0x18, 0x2a, 0x7a, 0xad,
	0xa9, 0x4c, 0xc8, 0x0c, 0x1d, 0xf2, 0x83, 0x3e, 0x5b, 0x81, 0xd3, 0xdc, 0x00, 0x11, 0xa6, 0xf7,
	0xeb, 0xa7, 0x68, 0x1d, 0x6d, 0xa3, 0xeb, 0xbb, 0xe8, 0x71, 0x75, 0x3b, 0xfb, 0x83, 0x13, 0x18,
	0xd6, 0xa5, 0x16, 0x59, 0x46, 0xe9, 0xcc, 0x42, 0x00, 0xa7, 0xad, 0x7b, 0xf8, 0x17, 0x46, 0xa2,
	0x2c, 0x65, 0x5d, 0x26, 0x94, 0xce, 0xfa, 0xb1, 0x63, 0xd2, 0x5d, 0x7c, 0x06, 0x00, 0x00, 0xff,
	0xff, 0x24, 0x73, 0x85, 0xae, 0xf7, 0x01, 0x00, 0x00,
}
