// Code generated by protoc-gen-go. DO NOT EDIT.
// source: herald.proto

package data

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
//Status is used to determine if experiments/samples have tagged processes, or if they have been announced via the message server
type Status int32

const (
	Status_UN_INITIALIZED Status = 0
	Status_untagged       Status = 1
	Status_tagged         Status = 2
	Status_announced      Status = 3
)

var Status_name = map[int32]string{
	0: "UN_INITIALIZED",
	1: "untagged",
	2: "tagged",
	3: "announced",
}

var Status_value = map[string]int32{
	"UN_INITIALIZED": 0,
	"untagged":       1,
	"tagged":         2,
	"announced":      3,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0fa959798cfd2bf0, []int{0}
}

//
//Comments are used to record a message history
type Comment struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Text                 string               `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fa959798cfd2bf0, []int{0}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Comment) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

//
//Process describes what to do to an experiment or sample
type Process struct {
	Complete             bool       `protobuf:"varint,1,opt,name=complete,proto3" json:"complete,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DependsOn            []*Process `protobuf:"bytes,3,rep,name=dependsOn,proto3" json:"dependsOn,omitempty"`
	History              []*Comment `protobuf:"bytes,4,rep,name=history,proto3" json:"history,omitempty"`
	Endpoint             string     `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Process) Reset()         { *m = Process{} }
func (m *Process) String() string { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()    {}
func (*Process) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fa959798cfd2bf0, []int{1}
}

func (m *Process) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process.Unmarshal(m, b)
}
func (m *Process) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process.Marshal(b, m, deterministic)
}
func (m *Process) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process.Merge(m, src)
}
func (m *Process) XXX_Size() int {
	return xxx_messageInfo_Process.Size(m)
}
func (m *Process) XXX_DiscardUnknown() {
	xxx_messageInfo_Process.DiscardUnknown(m)
}

var xxx_messageInfo_Process proto.InternalMessageInfo

func (m *Process) GetComplete() bool {
	if m != nil {
		return m.Complete
	}
	return false
}

func (m *Process) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Process) GetDependsOn() []*Process {
	if m != nil {
		return m.DependsOn
	}
	return nil
}

func (m *Process) GetHistory() []*Comment {
	if m != nil {
		return m.History
	}
	return nil
}

func (m *Process) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

//
//HeraldData is the base type, used by both Experiment and Sample
type HeraldData struct {
	Created              *timestamp.Timestamp `protobuf:"bytes,1,opt,name=created,proto3" json:"created,omitempty"`
	Label                string               `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	History              []*Comment           `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	Status               Status               `protobuf:"varint,4,opt,name=status,proto3,enum=data.Status" json:"status,omitempty"`
	Tags                 []*Process           `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HeraldData) Reset()         { *m = HeraldData{} }
func (m *HeraldData) String() string { return proto.CompactTextString(m) }
func (*HeraldData) ProtoMessage()    {}
func (*HeraldData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fa959798cfd2bf0, []int{2}
}

func (m *HeraldData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeraldData.Unmarshal(m, b)
}
func (m *HeraldData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeraldData.Marshal(b, m, deterministic)
}
func (m *HeraldData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeraldData.Merge(m, src)
}
func (m *HeraldData) XXX_Size() int {
	return xxx_messageInfo_HeraldData.Size(m)
}
func (m *HeraldData) XXX_DiscardUnknown() {
	xxx_messageInfo_HeraldData.DiscardUnknown(m)
}

var xxx_messageInfo_HeraldData proto.InternalMessageInfo

func (m *HeraldData) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *HeraldData) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *HeraldData) GetHistory() []*Comment {
	if m != nil {
		return m.History
	}
	return nil
}

func (m *HeraldData) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_UN_INITIALIZED
}

func (m *HeraldData) GetTags() []*Process {
	if m != nil {
		return m.Tags
	}
	return nil
}

//
//Experiment is used to describe a Nanopore sequencing run
type Experiment struct {
	Metadata             *HeraldData `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	OutputDirectory      string      `protobuf:"bytes,2,opt,name=output_directory,json=outputDirectory,proto3" json:"output_directory,omitempty"`
	Fast5OutputDirectory string      `protobuf:"bytes,3,opt,name=fast5_output_directory,json=fast5OutputDirectory,proto3" json:"fast5_output_directory,omitempty"`
	FastqOutputDirectory string      `protobuf:"bytes,4,opt,name=fastq_output_directory,json=fastqOutputDirectory,proto3" json:"fastq_output_directory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Experiment) Reset()         { *m = Experiment{} }
func (m *Experiment) String() string { return proto.CompactTextString(m) }
func (*Experiment) ProtoMessage()    {}
func (*Experiment) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fa959798cfd2bf0, []int{3}
}

func (m *Experiment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Experiment.Unmarshal(m, b)
}
func (m *Experiment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Experiment.Marshal(b, m, deterministic)
}
func (m *Experiment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Experiment.Merge(m, src)
}
func (m *Experiment) XXX_Size() int {
	return xxx_messageInfo_Experiment.Size(m)
}
func (m *Experiment) XXX_DiscardUnknown() {
	xxx_messageInfo_Experiment.DiscardUnknown(m)
}

var xxx_messageInfo_Experiment proto.InternalMessageInfo

func (m *Experiment) GetMetadata() *HeraldData {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Experiment) GetOutputDirectory() string {
	if m != nil {
		return m.OutputDirectory
	}
	return ""
}

func (m *Experiment) GetFast5OutputDirectory() string {
	if m != nil {
		return m.Fast5OutputDirectory
	}
	return ""
}

func (m *Experiment) GetFastqOutputDirectory() string {
	if m != nil {
		return m.FastqOutputDirectory
	}
	return ""
}

//
//Sample is used to describe a biological sample which is being sequenced as part of an Experiment
type Sample struct {
	Metadata             *HeraldData `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ParentExperiment     string      `protobuf:"bytes,2,opt,name=parentExperiment,proto3" json:"parentExperiment,omitempty"`
	Barcode              int32       `protobuf:"varint,3,opt,name=barcode,proto3" json:"barcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Sample) Reset()         { *m = Sample{} }
func (m *Sample) String() string { return proto.CompactTextString(m) }
func (*Sample) ProtoMessage()    {}
func (*Sample) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fa959798cfd2bf0, []int{4}
}

func (m *Sample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sample.Unmarshal(m, b)
}
func (m *Sample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sample.Marshal(b, m, deterministic)
}
func (m *Sample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sample.Merge(m, src)
}
func (m *Sample) XXX_Size() int {
	return xxx_messageInfo_Sample.Size(m)
}
func (m *Sample) XXX_DiscardUnknown() {
	xxx_messageInfo_Sample.DiscardUnknown(m)
}

var xxx_messageInfo_Sample proto.InternalMessageInfo

func (m *Sample) GetMetadata() *HeraldData {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Sample) GetParentExperiment() string {
	if m != nil {
		return m.ParentExperiment
	}
	return ""
}

func (m *Sample) GetBarcode() int32 {
	if m != nil {
		return m.Barcode
	}
	return 0
}

func init() {
	proto.RegisterEnum("data.Status", Status_name, Status_value)
	proto.RegisterType((*Comment)(nil), "data.Comment")
	proto.RegisterType((*Process)(nil), "data.Process")
	proto.RegisterType((*HeraldData)(nil), "data.HeraldData")
	proto.RegisterType((*Experiment)(nil), "data.Experiment")
	proto.RegisterType((*Sample)(nil), "data.Sample")
}

func init() { proto.RegisterFile("herald.proto", fileDescriptor_0fa959798cfd2bf0) }

var fileDescriptor_0fa959798cfd2bf0 = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x51, 0x6b, 0xd4, 0x40,
	0x10, 0xc7, 0x4d, 0x93, 0x4b, 0xee, 0xa6, 0xd7, 0x1a, 0x96, 0x22, 0xe1, 0x5e, 0x3c, 0x83, 0xe0,
	0x59, 0x25, 0x85, 0xb3, 0x82, 0xaf, 0xe2, 0x1d, 0x78, 0x20, 0xad, 0xa4, 0x15, 0xc1, 0x97, 0x63,
	0x2f, 0x3b, 0x4d, 0x03, 0xc9, 0x6e, 0x9a, 0x4c, 0xa0, 0x82, 0xdf, 0xc8, 0x6f, 0xe2, 0x9b, 0xdf,
	0x48, 0xb2, 0x49, 0x2e, 0xc5, 0x2b, 0x62, 0xdf, 0x76, 0xe6, 0xff, 0xff, 0x25, 0xf3, 0x9f, 0x5d,
	0x18, 0x5f, 0x63, 0xc1, 0x53, 0x11, 0xe4, 0x85, 0x22, 0xc5, 0x2c, 0xc1, 0x89, 0x4f, 0x9e, 0xc6,
	0x4a, 0xc5, 0x29, 0x9e, 0xe8, 0xde, 0xa6, 0xba, 0x3a, 0xa1, 0x24, 0xc3, 0x92, 0x78, 0x96, 0x37,
	0x36, 0xff, 0x2b, 0x38, 0x1f, 0x54, 0x96, 0xa1, 0x24, 0xf6, 0x0e, 0x46, 0x5b, 0xd5, 0x33, 0xa6,
	0xc6, 0x6c, 0x7f, 0x3e, 0x09, 0x1a, 0x3e, 0xe8, 0xf8, 0xe0, 0xb2, 0x73, 0x84, 0xbd, 0x99, 0x31,
	0xb0, 0x08, 0x6f, 0xc9, 0xdb, 0x9b, 0x1a, 0xb3, 0x51, 0xa8, 0xcf, 0xfe, 0x4f, 0x03, 0x9c, 0xcf,
	0x85, 0x8a, 0xb0, 0x2c, 0xd9, 0x04, 0x86, 0x91, 0xca, 0xf2, 0x14, 0x09, 0xf5, 0x87, 0x87, 0xe1,
	0xb6, 0xae, 0x59, 0xc9, 0x33, 0xec, 0xd8, 0xfa, 0xcc, 0x5e, 0xc1, 0x48, 0x60, 0x8e, 0x52, 0x94,
	0xe7, 0xd2, 0x33, 0xa7, 0xe6, 0x6c, 0x7f, 0x7e, 0x10, 0xd4, 0x79, 0x82, 0xf6, 0x8b, 0x61, 0xaf,
	0xb3, 0x17, 0xe0, 0x5c, 0x27, 0x25, 0xa9, 0xe2, 0xbb, 0x67, 0xdd, 0xb5, 0xb6, 0xb1, 0xc2, 0x4e,
	0xad, 0xa7, 0x40, 0x29, 0x72, 0x95, 0x48, 0xf2, 0x06, 0xfa, 0x6f, 0xdb, 0xda, 0xff, 0x65, 0x00,
	0x7c, 0xd4, 0xeb, 0x5b, 0x70, 0xe2, 0xec, 0x14, 0x9c, 0xa8, 0x40, 0x4e, 0x28, 0xfe, 0x63, 0x11,
	0x9d, 0x95, 0x1d, 0xc1, 0x20, 0xe5, 0x1b, 0x4c, 0xdb, 0x2c, 0x4d, 0x71, 0x77, 0x3e, 0xf3, 0x9f,
	0xf3, 0x3d, 0x07, 0xbb, 0x24, 0x4e, 0x55, 0xe9, 0x59, 0x53, 0x63, 0x76, 0x38, 0x1f, 0x37, 0xbe,
	0x0b, 0xdd, 0x0b, 0x5b, 0x8d, 0x3d, 0x03, 0x8b, 0x78, 0x5c, 0x7a, 0x83, 0xfb, 0xd6, 0xa2, 0x25,
	0xff, 0xb7, 0x01, 0xb0, 0xbc, 0xcd, 0xb1, 0x48, 0xf4, 0xbd, 0xbe, 0x86, 0x61, 0x86, 0xc4, 0x6b,
	0x63, 0x9b, 0xc6, 0x6d, 0xa8, 0x3e, 0x70, 0xb8, 0x75, 0xb0, 0x97, 0xe0, 0xaa, 0x8a, 0xf2, 0x8a,
	0xd6, 0x22, 0x29, 0x30, 0xd2, 0x73, 0x37, 0x79, 0x1e, 0x37, 0xfd, 0x45, 0xd7, 0x66, 0xa7, 0xf0,
	0xe4, 0x8a, 0x97, 0xf4, 0x76, 0xbd, 0x03, 0x98, 0x1a, 0x38, 0xd2, 0xea, 0xf9, 0xfd, 0xd4, 0xcd,
	0x2e, 0x65, 0xf5, 0xd4, 0xcd, 0x5f, 0x94, 0xff, 0x03, 0xec, 0x0b, 0x5e, 0x3f, 0x99, 0x07, 0xc6,
	0x39, 0x06, 0x37, 0xe7, 0x05, 0x4a, 0xea, 0x17, 0xd2, 0xc6, 0xd9, 0xe9, 0x33, 0x0f, 0x9c, 0x0d,
	0x2f, 0x22, 0x25, 0x50, 0x07, 0x18, 0x84, 0x5d, 0x79, 0xbc, 0x04, 0xbb, 0xb9, 0x06, 0xc6, 0xe0,
	0xf0, 0xcb, 0xd9, 0x7a, 0x75, 0xb6, 0xba, 0x5c, 0xbd, 0xff, 0xb4, 0xfa, 0xb6, 0x5c, 0xb8, 0x8f,
	0xd8, 0x18, 0x86, 0x95, 0x24, 0x1e, 0xc7, 0x28, 0x5c, 0x83, 0x01, 0xd8, 0xed, 0x79, 0x8f, 0x1d,
	0xc0, 0x88, 0x4b, 0xa9, 0x2a, 0x19, 0xa1, 0x70, 0xcd, 0x8d, 0xad, 0x5f, 0xcf, 0x9b, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xb8, 0x6d, 0x54, 0x4d, 0xaa, 0x03, 0x00, 0x00,
}
